Fix pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -18,9 +18,22 @@ include:
 .version_branch_with_tag_rules: &version_branch_with_tag_rules
   # Check if branch is a version branch
   - if: '$CI_COMMIT_REF_NAME =~ /^\d+\.\d+\.\d+$/'
-#    # Check if the commit has a tag that matches the version branch
-#    exists:
-#      - '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+\+build\.\d+$/'
+    exists:
+      - |
+        # This script block checks for the latest tag and verifies it matches version pattern
+        # Fetch tags to ensure the repository's tags are up to date
+        git fetch --tags
+        # Get the latest tag that points to the HEAD commit
+        LATEST_TAG=$(git describe --tags --match "*.*.*+build.*" $(git rev-list --tags --max-count=1))
+        # Check if the latest tag is a version tag
+        if [[ "$LATEST_TAG" =~ ^\d+\.\d+\.\d+\+build\.\d+$ ]]; then
+          echo "Latest tag is a version tag: $LATEST_TAG"
+          exit 0 # Success, the rule passes
+        else
+          echo "Latest tag is not a version tag."
+          exit 1 # Failure, the job will not run
+        fi
+
 
 #.new_version_rules: &new-version-rules
 #  - if: '$CI_COMMIT_BRANCH == "develop" || $CI_COMMIT_BRANCH == $MAIN_BRANCH_NAME'
@@ -46,16 +59,6 @@ tmp_test:
   script:
     - ls -la
     - echo $CI_COMMIT_TAG
-    - |
-      LAST_COMMIT=$(git rev-parse HEAD)
-      echo "Last commit $LAST_COMMIT"
-
-      TAG=$(git tag --contains $LAST_COMMIT)
-      if [ -z "$TAG" ]; then
-        echo "No tag."
-      else
-        echo "Last tag : $TAG"
-      fi
   rules:
     - *version_branch_with_tag_rules
 
