Fix install

diff --git a/cli/install b/cli/install
--- a/cli/install
+++ b/cli/install
@@ -1,24 +1,44 @@
 #!/usr/bin/env bash
 
-# Find current file directory
-# supporting symlinks
-WEX_DIR_CLI="$(realpath "$(dirname "$(readlink -f ${BASH_SOURCE[0]})")")/"
+# Exit immediately if a command exits with a non-zero status.
+set -e
 
+# Find the current file directory, supporting symlinks
+WEX_DIR_CLI="$(realpath "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")")/"
+
+# Source initialization scripts
 . "${WEX_DIR_CLI}/_init.sh"
 . "${WEX_DIR_CLI}/_init_sudo.sh"
 
+# Set WEX_DIR_ROOT
 WEX_DIR_ROOT="$(realpath "${WEX_DIR_CLI}../")/"
 
-echo "Checking python requirements..."
-if ! command -v pip >/dev/null 2>&1; then
+echo "Checking Python requirements..."
+
+# Function to check if a command exists
+command_exists() {
+  command -v "$1" >/dev/null 2>&1
+}
+
+# Install pip if not installed
+if ! command_exists pip; then
     echo "Installing pip..."
     sudo apt-get update
-    sudo apt-get -y install procps python3-pip python3-venv
+    sudo apt-get -y install python3-pip python3-venv
 fi
 
-# Create and activate virtual env.
-python3 -m venv ${WEX_DIR_ROOT}.wex/python/venv
-source ${WEX_DIR_ROOT}.wex/python/venv/bin/activate
+# Install procps if not installed
+if ! command_exists ps; then
+    echo "Installing procps..."
+    sudo apt-get update
+    sudo apt-get -y install procps
+fi
+
+# Create and activate virtual environment
+VENV_PATH="${WEX_DIR_ROOT}.wex/python/venv"
+python3 -m venv "$VENV_PATH"
+# shellcheck disable=SC1090
+source "${VENV_PATH}/bin/activate"
 
 echo "Installing python requirements..."
 pip install "${WEX_DIR_ROOT}" -r "${WEX_DIR_ROOT}requirements.txt"
